config/routes.rb
Rails.application.routes.draw do
  resources :messages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.all
  end

  def show
    @message = Message.find(params[:id])
  end

  def new
    @message = Message.new
  end

  def edit
    @message = Message.find(params[:id])
  end

  def create
    @message = Message.new(message_params)

    @message.save
    redirect_to messages_path
  end

  def update
    @message = Message.find(params[:id])

    @message.update(message_params)
    redirect_to messages_path
  end

  def destroy
    @message = Message.find(params[:id])

    @message.destroy
    redirect_to messages_path
  end

  private

  def message_params
    params.require(:message).permit(:body, :sender, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ValidationsExercise</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= form_for @message, url: message_path(@message), method: :put do |form| %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body, id: :message_body %>
  </div>

  <div class="field">
    <%= form.label :sender %>
    <%= form.text_field :sender, id: :message_sender %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :message_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Sender</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.body %></td>
        <td><%= message.sender %></td>
        <td><%= message.email %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= form_for @message, url: messages_path, method: :post do |form| %>

  <%= form.label :body %>
  <%= form.text_field :body %>

  <%= form.label :sender %>
  <%= form.text_field :sender %>

  <%= form.label :email %>
  <%= form.text_field :email %>

  <p><%= form.submit %></p>
<% end %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @message.sender %>
</p>

<p>
  <strong>Email:</strong>
  <%= @message.email %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>